<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Reltio_POC_Suite]">
  <test name="REltio_POC_Test(failed)">
    <classes>
      <class name="com.Reltio.TestScripts.LoginWithInvalidCredentials">
        <methods>
          <include name="getResult"/>
          <include name="setUp"/>
          <include name="Login"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- com.Reltio.TestScripts.LoginWithInvalidCredentials -->
      <class name="com.Reltio.TestScripts.Advanced_Search_with_ZeroResult">
        <methods>
          <include name="getResult"/>
          <include name="Exec_Inv_Search"/>
        </methods>
      </class> <!-- com.Reltio.TestScripts.Advanced_Search_with_ZeroResult -->
      <class name="com.Reltio.TestScripts.Advanced_Search_with_Valid_Data">
        <methods>
          <include name="Exec_Search"/>
          <include name="getResult"/>
        </methods>
      </class> <!-- com.Reltio.TestScripts.Advanced_Search_with_Valid_Data -->
      <class name="com.Reltio.TestScripts.LoginWithValidCredentials">
        <methods>
          <include name="LoginValid"/>
          <include name="getResult"/>
        </methods>
      </class> <!-- com.Reltio.TestScripts.LoginWithValidCredentials -->
    </classes>
  </test> <!-- REltio_POC_Test(failed) -->
</suite> <!-- Failed suite [Reltio_POC_Suite] -->
